
const sidebars = {
  
  // Automatically create from  docs dir
  notes: [{type: 'autogenerated', dirName: '.'}],


  /* But manually can be defined.
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
  */
};


module.exports = sidebars;
